### ISSUE TITLE
Does this work on the LDRobot D100 LD14

### ISSUE THREAD

**Issue by hpssjellis** [henjin0/Lidar_LD06_for_Arduino#1]
Does this code work with the [LDRobot D100 LD14](https://www.ldrobot.com/product/en/124)  ?

I am having some issues with the Serial2 setting,

My Arudino is the PortentaH7 which has a Serial1 default along with Serial0.

**Comment by henjin0** [comment]
Sorry, I have not checked the operation of D100 and LD14 because I don't have them.

**Comment by henjin0** [comment]
Closed because discussion is complete.
