### ISSUE TITLE
Hi is this compatible with arduino ?

### ISSUE THREAD

**Issue by meltoner** [henjin0/Lidar_LD06_for_Arduino#2]
m5 atom might suggest its not. i also get cannot find vector which as i read is c++ so due to these obstacles coudn't use it to read data from arduino. could you please clarify so i am not trying in vain?

**Comment by henjin0** [comment]
I haven't touched anything since I checked it working 2 years ago, so it may not work.
I can't decided whether to support it or not, but it would be great if you could write the error text and environment.

**Comment by meltoner** [comment]
Hi Henjin, instead of an arduino i used an esp32, and was able to make it work! it seems esp32 supports c++ and the vector. i think its great that you wrote it and its very usefull for the community! the m5 staff aren't necessary can be removed. For some reason the d06forarduino instead of cpp extension has imo and without an imo it wont compile. but since i managed it now only a matter of curiosity.
