### ISSUE TITLE
Hi is this compatible with arduino ? m5 atom might suggest its not.

### ISSUE THREAD

**Issue by TheGoldenV** [henjin0/Lidar_LD06_for_Arduino#3]
[Hi is this compatible with arduino ?](https://coder.social/henjin0/lidar_ld06_for_arduino/issues/2)
m5 atom might suggest its not. i also get cannot find vector which as i read is c++ so due to these obstacles coudn't use it to read data from arduino. could you please clarify so i am not trying in vain?

**Comment by henjin0** [comment]
I have only developped that the M5Atom in the sample code works. I do not intend for it to work with a regular Arduino board, but rather I have written "Arduino" in the repository name with the intention that it is code that can be created from the Arduino IDE.

I can't see what your error is, so I can't discuss anything with you. Also, this is a hobby project and is not currently being developed, at least not yet. I would be glad if you could fork it and improve it or send me a pull request with the fix!

**Comment by henjin0** [comment]
Closed as two weeks have elapsed.
